spring:
 application:
  name: "eurekaserver"
 config:
  import: "optional:configserver:http://localhost:8071/"

management:
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"