spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

accounts:
  message: "Welcome to EazyBank Loans related QA APIs "
  contactDetails:
    name: "Smithaaaa Ray - QA Lead"
    email: "smithaaaa@eazybank.com"
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371