     
build:
  version: "3.0"
cards:
  message: "Welcome to EazyBank Cards related local APIs "
  contactDetails:
    name: "John Abraham - Cards Developer"
    email: "john@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345