
build:
  version: "2.0"

loans:
  message: "Welcome to EazyBank Loans related QA APIs "
  contactDetails:
    name: "Smithaaaa Ray - QA Lead"
    email: "smithaaaa@eazybank.com"
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371