# Application properties for Spring Cloud Config Server

spring:
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
  application:
    name: "configserver"
  profiles:
    active: git  # Activating the git profile

  cloud:
    config:
      server:
        git:
          uri: "https://github.com/Net-Freaker/eazybytes-config"  # URI of your Git repository
          default-label: main  # Default branch name
          timeout: 5  # Timeout for Git operations in seconds
          clone-on-start: true  # Clones the repository on server start
          force-pull: true  # Forces a pull of changes on server start

server:
  port: 8071  # Port on which the config server will run

encrypt:
  key: "J543JKH3Q43KJQXSDF4REJ"  # Encryption key for secure communication (if used)
management:
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"