server:
  port: 8090

spring:

 application:
  name: "loans"
 profiles:
  active: "qa"
 datasource:
    url: jdbc:h2:mem:testdb  # Use in-memory database for development
    driverClassName: org.h2.Driver
    username: sa
    password:  # Optional, leave blank for in-memory database
    initialize: true  # Enable automatic schema initialization

 h2:
    console:
      enabled: true  # Enable H2 console for database management

 jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update  # Update schema if necessary
    show-sql: true  # Optional, enable SQL logging for debugging
 config:
    import: "optional:configserver:http://localhost:8071/"
   
management:
  endpoint:
   shutdown:
      enabled: true
   health:
      probes:
        enabled: true
  info:
   env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
endpoints:
 shutdown: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
info:
 app:
  name: "Loans"
  description: "My Own Bank's Loan' Application"
  version: "1.0.0"
logging:
  level:
    com:
      microservices:
        loans: DEBUG 
  