
spring:
 security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:7080/realms/master/protocol/openid-connect/certs"
 data:
    redis:
      connect-timeout: 2s
      host: localhost
      port: 6379
      timeout: 1s
  
 application:
  name: "gatewayserver"
 cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
      discovery:
        locator:
          enabled: false #true for default behaviours like 8072/actuatot/gateway/routes/
          lowerCaseServiceId: true
 config:
    import: "optional:configserver:http://localhost:8071/"
management:
  endpoint:
   gateway:
      enabled: true
  info:
   env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

info:
 app:
  name: "gatewayserver"
  description: "My Own Bank Gateway Server Application"
  version: "1.0.0"
    
logging:
  level:
    com:
      microservices:
        gatewayserver: DEBUG          
   
resilience4j.circuitbreaker:
  configs:
    default:  #this configuration for all microservice if you want for perticular microservice config then you can place name 
      slidingWindowSize: 10 #atleast monitor this many request to modify status
      permittedNumberOfCallsInHalfOpenState: 2 #to allow this request to go back to open or closed
      failureRateThreshold: 50
      waitDurationInOpenState: 10000
  